language: java
deploy:
  provider: releases
  api_key:
    secure: YAQ9uP6WliPZscnQfQ9GokPWl1G2nsyNKEi2XZwiNy9zJk+Q1B0V6P7F8dvxIFRQf7FfMVZJD7It9hBFEoKdhNiiG+Fic0nAKQK872Cc5wCMW/4GWZSyIpF55hWi4a1xkOpU6CunOnxC/uT1rFjkK+Uc3pIMylXzabEvbDhMk5w=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-versions-plugin
notifications:
  hipchat:
    rooms:
      secure: G8OaTyfe6EXDMxcyztaQsVQahUgMRcn/L/tPB8eg5lecISQ8YN3/b/7mB+D/iShmeaUn6SgAiwWxXC+q7p7ZWucxno0MtjbsAVhZhzkT4fn/gHITTCqvo9Vl2rosfF7dqdI6Uo0Kl5jP4OGCOF617IFkV0IMNmvFpXry7qbfCCg=
