language: java
deploy:
  provider: releases
  api_key:
    secure: YAQ9uP6WliPZscnQfQ9GokPWl1G2nsyNKEi2XZwiNy9zJk+Q1B0V6P7F8dvxIFRQf7FfMVZJD7It9hBFEoKdhNiiG+Fic0nAKQK872Cc5wCMW/4GWZSyIpF55hWi4a1xkOpU6CunOnxC/uT1rFjkK+Uc3pIMylXzabEvbDhMk5w=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-versions-plugin
notifications:
  slack:
    secure: o5QFBHMRhyblRIwuxRB+rfqj9GnyENAS0BgXjs7txgreE8v8fcoDQJQ8RFdXtK3w6Y1QEgFq+diZ4zlQRRXMzH3qC16mEfdOdiVtfnxYq2VvRIRyUVpPAteBGejaHpCNBMDR24ZTudSwaAxAuALuNDe4KieA6BuTi46rt7LPKuU=
